"""new fields in user model

Revision ID: 4464191b42d6
Revises: 7817bd6db29b
Create Date: 2019-05-21 14:40:22.281794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4464191b42d6'
down_revision = '7817bd6db29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
